name: remind_me
description: A Flutter project to manage Student's College Life.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  liquid_swipe: ^2.1.0
  animations: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  provider: ^5.0.0
  uuid: ^3.0.4
  shared_preferences: ^2.0.5
  file_picker: ^3.0.1
  path_provider: ^2.0.1
  flutter_local_notifications: ^5.0.0+4
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  percent_indicator: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/remind_me_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/img/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/font/Product_Sans_Bold.ttf
          weight: 700
        - asset: assets/font/Product_Sans_Regular.ttf
    - family: Righteous
      fonts:
        - asset: assets/font/Righteous-Regular.ttf
          weight: 400
