name: remind_me
description: A Flutter project to manage Student's College Life.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  liquid_swipe: ^3.0.0
  animations: ^2.0.7
  provider: ^6.0.5
  uuid: ^3.0.7
  shared_preferences: ^2.0.20
  file_picker: ^5.2.6
  path_provider: ^2.0.14
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  percent_indicator: ^4.2.3
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/remind_me_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/img/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/font/Product_Sans_Bold.ttf
          weight: 700
        - asset: assets/font/Product_Sans_Regular.ttf
    - family: Righteous
      fonts:
        - asset: assets/font/Righteous-Regular.ttf
          weight: 400
